apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server-gtnh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-server-gtnh
  template:
    metadata:
      labels:
        app: minecraft-server-gtnh
    spec:
      containers:
        - name: minecraft-gtnh
          image: adafww/minecraft-server-gtnh:latest
          ports:
            - containerPort: 25565
          volumeMounts:
            - name: data-volume
              mountPath: /app/World
            - name: data-journeymap-volume
              mountPath: /app/config/JourneyMapServer
          command: ["/bin/sh", "-c"]
          args:
            - |
              while true
              do
                 java -Xms4G -Xmx4G -Dfml.readTimeout=180 @java9args.txt nogui
                  echo "If you want to completely stop the server process now, press Ctrl+C before the time is up!"
                  echo "Rebooting in:"
                  for i in 12 11 10 9 8 7 6 5 4 3 2 1
                  do
                      echo "$i..."
                      sleep 1
                  done
                  echo "Rebooting now!"
              done
#          resources:
#            limits:
#              memory: 4Gi
      volumes:
        - name: data-volume
          hostPath:
            path: /minegtnh/World
        - name: data-journeymap-volume
          hostPath:
            path: /minegtnh/JourneyMapServer