apiVersion: v1
kind: Service
metadata:
  name: minecraft-gtnh-nodeport
spec:
  type: NodePort
  ports:
    - port: 25565
      targetPort: 25565
      nodePort: 31000
  selector:
    app: minecraft-server-gtnh